apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

images:
  - name: localhost:5000/micro/discovery
    newName: localhost:5000/micro/discovery
    newTag: "1.0.0"
  - name: localhost:5000/micro/log
    newName: localhost:5000/micro/log
    newTag: "1.0.0"
  - name: localhost:5000/micro/gateway
    newName: localhost:5000/micro/gateway
    newTag: "1.0.0"

